var animationFrames = {
    "actions": {
        "easy": {
            "1": "images/animations/relax1.png",
            "2": "images/animations/relax2.png",
            "3": "images/animations/relax3.png",
            "4": "images/animations/relax4.png",
            "5": "images/animations/relax5.png",
            "6": "images/animations/relax6.png",
            "7": "images/animations/relax7.png",
            "8": "images/animations/relax8.png",
            "9": "images/animations/relax9.png",
            "10": "images/animations/relax10.png",
        },
        "hard": {
            "1": "images/animations/work1.png",
            "2": "images/animations/work2.png",
            "3": "images/animations/work3.png",
            "4": "images/animations/work4.png",
            "5": "images/animations/work5.png",
            "6": "images/animations/work6.png",
            "7": "images/animations/work7.png",
            "8": "images/animations/work8.png",
            "9": "images/animations/work9.png",
            "10": "images/animations/work10.png",
            "11": "images/animations/work11.png",
            "12": "images/animations/work12.png",
            "13": "images/animations/work13.png",
            "14": "images/animations/work14.png",
            "15": "images/animations/work15.png",
            "16": "images/animations/work16.png",
            "17": "images/animations/work17.png",
            "18": "images/animations/work18.png",
            "19": "images/animations/work19.png",
        },
        "medium": {
            "1": "images/animations/stretch1.png",
            "2": "images/animations/stretch2.png",
            "3": "images/animations/stretch3.png",
            "4": "images/animations/stretch4.png",
        },
    },
    "slots": {
        "easy_in": {
            "1": "images/animations/slots14.png",
            "2": "images/animations/slots15.png",
            "3": "images/animations/slots16.png",
            "4": "images/animations/slots17.png",
            "5": "images/animations/slots18.png",
            "6": "images/animations/slots19.png",
            "7": "images/animations/slots20.png",
            "8": "images/animations/slots21.png",
            "9": "images/animations/slots22.png",
            "10": "images/animations/slots23.png",
            "11": "images/animations/slots24.png",
            "12": "images/animations/slots25.png",
            "13": "images/animations/slots26.png",
        },
        "medium_in": { 
            "1": "images/animations/slots14.png",
            "2": "images/animations/slots40.png",
            "3": "images/animations/slots41.png",
            "4": "images/animations/slots42.png",
            "5": "images/animations/slots43.png",
            "6": "images/animations/slots44.png",
            "7": "images/animations/slots45.png",
            "8": "images/animations/slots46.png",
            "9": "images/animations/slots47.png",
            "10": "images/animations/slots48.png",
            "11": "images/animations/slots49.png",
            "12": "images/animations/slots50.png",
            "13": "images/animations/slots51.png",
        },
        "hard_in": {
            "1": "images/animations/slots64.png",
            "2": "images/animations/slots65.png",
            "3": "images/animations/slots66.png",
            "4": "images/animations/slots67.png",
            "5": "images/animations/slots68.png",
            "6": "images/animations/slots69.png",
            "7": "images/animations/slots70.png",
            "8": "images/animations/slots71.png",
            "9": "images/animations/slots72.png",
            "10": "images/animations/slots73.png",
            "11": "images/animations/slots74.png",
            "12": "images/animations/slots75.png",
            "13": "images/animations/slots1.png",
        },
        "spin": {
            "1": "images/animations/slotspinning1.png",
            "2": "images/animations/slotspinning2.png",
            "3": "images/animations/slotspinning3.png",
            "4": "images/animations/slotspinning4.png",
            "5": "images/animations/slotspinning5.png",
            "6": "images/animations/slotspinning6.png",
            "7": "images/animations/slotspinning7.png",
            "8": "images/animations/slotspinning8.png",
            "9": "images/animations/slotspinning9.png",
            "10": "images/animations/slotspinning10.png",
            "11": "images/animations/slotspinning11.png",
            "12": "images/animations/slotspinning12.png",
            "13": "images/animations/slotspinning13.png",
            "14": "images/animations/slotspinning14.png",
            "15": "images/animations/slotspinning15.png",
            "16": "images/animations/slotspinning16.png",
            "17": "images/animations/slotspinning17.png",
            "18": "images/animations/slotspinning18.png",
            "19": "images/animations/slotspinning19.png",
            "20": "images/animations/slotspinning20.png",
            "21": "images/animations/slotspinning21.png",
            "22": "images/animations/slotspinning22.png",
            "23": "images/animations/slotspinning23.png",
            "24": "images/animations/slotspinning24.png",
            "25": "images/animations/slotspinning25.png",
            "26": "images/animations/slotspinning26.png",
            "27": "images/animations/slotspinning27.png",
            "28": "images/animations/slotspinning28.png",
            "29": "images/animations/slotspinning29.png",
            "30": "images/animations/slotspinning30.png",
        },
    },
    "happy": {
        "idle": {
            "1": "images/animations/happy1.png",
        },
        "breath": {
            "1": "images/animations/happy2.png",
            "2": "images/animations/happy3.png",
            "3": "images/animations/happy4.png",
        },
        "blink": {
            "1": "images/animations/happy6.png",
            "2": "images/animations/happy7.png",
            "3": "images/animations/happy8.png",
            "4": "images/animations/happy9.png",
            "5": "images/animations/happy10.png",
        },
    },
    "meh": {
        "idle": {
            "1": "images/animations/meh1.png",
        },
        "breath": {
            "1": "images/animations/meh2.png",
            "2": "images/animations/meh3.png",
            "3": "images/animations/meh4.png",
        },
        "blink": {
            "1": "images/animations/meh6.png",
            "2": "images/animations/meh7.png",
            "3": "images/animations/meh8.png",
            "4": "images/animations/meh9.png",
            "5": "images/animations/meh10.png",
        },
    },
    "angry": {
        "idle": {
            "1": "images/animations/angry1.png",
        },
        "breath": {
            "1": "images/animations/angry2.png",
            "2": "images/animations/angry3.png",
            "3": "images/animations/angry4.png",
        },
        "blink": {
            "1": "images/animations/angry6.png",
            "2": "images/animations/angry7.png",
            "3": "images/animations/angry8.png",
            "4": "images/animations/angry9.png",
            "5": "images/animations/angry10.png",
        },
    },
    "furious": {
        "idle": {
            "1": "images/animations/furious1.png",
        },
        "breath": {
            "1": "images/animations/furious2.png",
            "2": "images/animations/furious3.png",
            "3": "images/animations/furious4.png",
        },
        "blink": {
            "1": "images/animations/furious6.png",
            "2": "images/animations/furious7.png",
            "3": "images/animations/furious8.png",
            "4": "images/animations/furious9.png",
            "5": "images/animations/furious10.png",
        },
    },
    "hellpossessed": {
        "idle": {
            "1": "images/animations/furious1.png",
        },
        "breath": {
            "1": "images/animations/furious2.png",
            "2": "images/animations/furious3.png",
            "3": "images/animations/furious4.png",
        },
        "blink": {
            "1": "images/animations/furious6.png",
            "2": "images/animations/furious7.png",
            "3": "images/animations/furious8.png",
            "4": "images/animations/furious9.png",
            "5": "images/animations/furious10.png",
        },
    },
    "blissful": {
        "idle": {
            "1": "images/animations/blissful1.png",
        },
        "breath": {
            "1": "images/animations/blissful2.png",
            "2": "images/animations/blissful3.png",
            "3": "images/animations/blissful4.png",
        },
        "blink": {
            "1": "images/animations/blissful6.png",
            "2": "images/animations/blissful7.png",
            "3": "images/animations/blissful8.png",
            "4": "images/animations/blissful9.png",
            "5": "images/animations/blissful10.png",
        },
    },
};

var bgAnimations = {
    "hellpossessed": {
        "1": "images/animations/ring1.png",
        "2": "images/animations/ring2.png",
        "3": "images/animations/ring3.png",
        "4": "images/animations/ring4.png",
        "5": "images/animations/ring5.png",
        "6": "images/animations/ring6.png",
        "7": "images/animations/ring1.png",
        "8": "images/animations/ring2.png",
        "9": "images/animations/ring3.png",
        "10": "images/animations/ring4.png",
        "11": "images/animations/ring5.png",
        "12": "images/animations/ring6.png",
        "13": "images/animations/ring1.png",
        "14": "images/animations/ring2.png",
        "15": "images/animations/ring3.png",
        "16": "images/animations/ring4.png",
        "17": "images/animations/ring5.png",
        "18": "images/animations/ring6.png",
        "19": "images/animations/ring1.png",
        "20": "images/animations/ring2.png",
        "21": "images/animations/ring3.png",
        "22": "images/animations/ring4.png",
        "23": "images/animations/ring5.png",
        "24": "images/animations/ring6.png",
    },
};

var animationTimings = {
    "actions": {
        "easy": {
            "1": 3200,
            "2": 64,
            "3": 640,
            "4": 128,
            "5": 1200,
            "6": 64,
            "7": 32,
            "8": 200,
            "9": 32,
            "10": 64,
        },
        "hard": {
            "1": 1600,
            "2": 64,
            "3": 512,
            "4": 64,
            "5": 512,
            "6": 64,
            "7": 64,
            "8": 32,
            "9": 32,
            "10": 64,
            "11": 64,
            "12": 1600,
            "13": 64,
            "14": 256,
            "15": 64,
            "16": 1600,
            "17": 64,
            "18": 512,
            "19": 64,
        },
        "medium": {
            "1": 2000,
            "2": 64,
            "3": 1000,
            "4": 64,
        },
    },
    "slots": {
        "easy_in": {
            "1": 32,
            "2": 32,
            "3": 32,
            "4": 32,
            "5": 64,
            "6": 64,
            "7": 64,
            "8": 64,
            "9": 64,
            "10": 64,
            "11": 128,
            "12": 128,
            "13": 1000,
        },
        "medium_in": {
            "1": 32,
            "2": 32,
            "3": 32,
            "4": 32,
            "5": 64,
            "6": 64,
            "7": 64,
            "8": 64,
            "9": 64,
            "10": 64,
            "11": 128,
            "12": 128,
            "13": 1000,

        },
        "hard_in": {
            "1": 32,
            "2": 32,
            "3": 32,
            "4": 32,
            "5": 64,
            "6": 64,
            "7": 64,
            "8": 64,
            "9": 64,
            "10": 64,
            "11": 128,
            "12": 128,
            "13": 1000,
        },
        "spin": {
            "1": 16,
            "2": 16,
            "3": 16,
            "4": 16,
            "5": 16,
            "6": 16,
            "7": 16,
            "8": 16,
            "9": 16,
            "10": 16,
            "11": 16,
            "12": 16,
            "13": 16,
            "14": 16,
            "15": 16,
            "16": 16,
            "17": 16,
            "18": 16,
            "19": 16,
            "20": 16,
            "21": 16,
            "22": 16,
            "23": 16,
            "24": 16,
            "25": 16,
            "26": 16,
            "27": 16,
            "28": 16,
            "29": 16,
            "30": 16,
        },
    },
    "happy": {
        "idle": {
            "1": 9999,
        },
        "breath": {
            "1": 32,
            "2": 420,
            "3": 64,
        },
        "blink": {
            "1": 50,
            "2": 32,
            "3": 200,
            "4": 32,
            "5": 50,
        }
    },
    "meh": {
        "idle": {
            "1": 9999,
        },
        "breath": {
            "1": 32,
            "2": 420,
            "3": 64,
        },
        "blink": {
            "1": 50,
            "2": 32,
            "3": 200,
            "4": 32,
            "5": 50,
        }
    },
    "angry": {
        "idle": {
            "1": 9999,
        },
        "breath": {
            "1": 32,
            "2": 420,
            "3": 64,
        },
        "blink": {
            "1": 50,
            "2": 32,
            "3": 200,
            "4": 32,
            "5": 50,
        }
    },
    "furious": {
        "idle": {
            "1": 9999,
        },
        "breath": {
            "1": 32,
            "2": 420,
            "3": 64,
        },
        "blink": {
            "1": 50,
            "2": 32,
            "3": 200,
            "4": 32,
            "5": 50,
        }
    },
    "hellpossessed": {
        "idle": {
            "1": 9999,
        },
        "breath": {
            "1": 32,
            "2": 420,
            "3": 64,
        },
        "blink": {
            "1": 50,
            "2": 32,
            "3": 200,
            "4": 32,
            "5": 50,
        }
    },
    "blissful": {
        "idle": {
            "1": 9999,
        },
        "breath": {
            "1": 32,
            "2": 420,
            "3": 64,
        },
        "blink": {
            "1": 50,
            "2": 32,
            "3": 200,
            "4": 32,
            "5": 50,
        }
    },
};

var animationOthers = {
    "happy": {
        "blink": 0.2, // 20% chance each second
    },
    "meh": {
        "blink": 0.2, 
    },
    "angry": {
        "blink": 0.15, 
    },
    "furious": {
        "blink": 0.1, 
    },
    "hellpossessed": {
        "blink": 0.05,
    },
    "blissful": {
        "blink": 0.2, 
    }
};

var breathCycles = {
    "happy": 4000,
    "meh": 4000,
    "angry": 4000,
    "furious": 3000,
    "hellpossessed": 2000,
    "blissful": 6000,
};

var gradientBackgrounds = {
    "actions": [
        "#000000",
        "#000000",
    ],
    "slots": [
        "#000000",
        "#000000",
    ],
    "happy": [
        "#000000",
        "#000000",
    ],
    "meh": [
        "#110000",
        "#220000",
    ],
    "angry": [
        "#220000",
        "#440000",
    ],
    "furious": [
        "#440000",
        "#880000",
    ],
    "hellpossessed": [
        "#880000",
        "#ff0000",
    ],
    "blissful": [
        "#ff00ff",
        "#00ffff",
    ],
};

var stateIntervals = [
    "happy",
    "meh",
    "meh",
    "angry",
    "angry",
    "angry",
    "angry",
    "furious",
    "furious",
    "furious",
    "furious",
    "hellpossessed",
];